KENYA_COUNTIES = [
    {"name": "Baringo", "code": "030", "region": "Rift Valley"},
    {"name": "Bomet", "code": "036", "region": "Rift Valley"},
    {"name": "Bungoma", "code": "039", "region": "Western"},
    {"name": "Busia", "code": "040", "region": "Western"},
    {"name": "Elgeyo-Marakwet", "code": "028", "region": "Rift Valley"},
    {"name": "Embu", "code": "014", "region": "Eastern"},
    {"name": "Garissa", "code": "007", "region": "North Eastern"},
    {"name": "Homa Bay", "code": "043", "region": "Nyanza"},
    {"name": "Isiolo", "code": "011", "region": "Eastern"},
    {"name": "Kajiado", "code": "034", "region": "Rift Valley"},
    {"name": "Kakamega", "code": "037", "region": "Western"},
    {"name": "Kericho", "code": "035", "region": "Rift Valley"},
    {"name": "Kiambu", "code": "022", "region": "Central"},
    {"name": "Kilifi", "code": "003", "region": "Coast"},
    {"name": "Kirinyaga", "code": "020", "region": "Central"},
    {"name": "Kisii", "code": "045", "region": "Nyanza"},
    {"name": "Kisumu", "code": "042", "region": "Nyanza"},
    {"name": "Kitui", "code": "015", "region": "Eastern"},
    {"name": "Kwale", "code": "002", "region": "Coast"},
    {"name": "Laikipia", "code": "031", "region": "Rift Valley"},
    {"name": "Lamu", "code": "005", "region": "Coast"},
    {"name": "Machakos", "code": "016", "region": "Eastern"},
    {"name": "Makueni", "code": "017", "region": "Eastern"},
    {"name": "Mandera", "code": "009", "region": "North Eastern"},
    {"name": "Marsabit", "code": "010", "region": "Eastern"},
    {"name": "Meru", "code": "012", "region": "Eastern"},
    {"name": "Migori", "code": "044", "region": "Nyanza"},
    {"name": "Mombasa", "code": "001", "region": "Coast"},
    {"name": "Murang'a", "code": "021", "region": "Central"},
    {"name": "Nairobi", "code": "047", "region": "Nairobi"},
    {"name": "Nakuru", "code": "032", "region": "Rift Valley"},
    {"name": "Nandi", "code": "029", "region": "Rift Valley"},
    {"name": "Narok", "code": "033", "region": "Rift Valley"},
    {"name": "Nyamira", "code": "046", "region": "Nyanza"},
    {"name": "Nyandarua", "code": "018", "region": "Central"},
    {"name": "Nyeri", "code": "019", "region": "Central"},
    {"name": "Samburu", "code": "025", "region": "Rift Valley"},
    {"name": "Siaya", "code": "041", "region": "Nyanza"},
    {"name": "Taita-Taveta", "code": "006", "region": "Coast"},
    {"name": "Tana River", "code": "004", "region": "Coast"},
    {"name": "Tharaka-Nithi", "code": "013", "region": "Eastern"},
    {"name": "Trans Nzoia", "code": "026", "region": "Rift Valley"},
    {"name": "Turkana", "code": "023", "region": "Rift Valley"},
    {"name": "Uasin Gishu", "code": "027", "region": "Rift Valley"},
    {"name": "Vihiga", "code": "038", "region": "Western"},
    {"name": "Wajir", "code": "008", "region": "North Eastern"},
    {"name": "West Pokot", "code": "024", "region": "Rift Valley"},
]